/**:
  ros__parameters:
    # 행동별 파라미터 수정자 설정
    # Baseline은 smppi_params.yaml에서 로드하고, 여기서는 multiplier/override만 정의
    
    behavior_modifiers:
      1:  # 전진 (기본값 사용)
        description: "Normal forward movement"
        multipliers: {}  # 모든 값 1.0 (기본값 사용)
        overrides: {}
        
      2:  # 후진
        description: "Reverse movement"
        multipliers:
          goal_weight: 1.7              # 170% (더 정확하게)
          xy_goal_tolerance: 0.5        # 50% (더 엄격하게)
          lookahead_base_distance: 0.6  # 60% (짧게)
        overrides:
          max_linear_velocity: 0.0      # 전진 속도 0
          min_linear_velocity: -1.5     # 후진 속도 -1.5 m/s
          respect_reverse_heading: true
          
      3:  # 전진 정밀 pose tracking  
        description: "Precise forward tracking"
        multipliers:
          max_linear_velocity: 0.66     # 33% (느리게)
          goal_weight: 2.5              # 250% (매우 정확하게)
          lookahead_base_distance: 0.6  # 60% (짧게)
          xy_goal_tolerance: 0.4        # 40% (엄격하게)
          goal_reached_threshold: 0.6   # 50% (더 정밀한 도달 판정)
        overrides:
          min_linear_velocity: 0.0
          
      4:  # 후진 정밀 pose tracking
        description: "Precise reverse tracking"
        multipliers:
          goal_weight: 3.0              # 300% (매우 정확하게)
          xy_goal_tolerance: 0.3        # 30% (매우 엄격하게)
          lookahead_base_distance: 0.5  # 50% (매우 짧게)
          goal_reached_threshold: 0.2   # 40% (매우 정밀한 도달 판정)
        overrides:
          max_linear_velocity: 0.0      # 전진 속도 0
          min_linear_velocity: -0.8     # 느린 후진 속도
          respect_reverse_heading: true
          
      5:  # 가속(빠르게 전진)
        description: "Fast forward movement"
        multipliers:
          max_linear_velocity: 1.3      # 130% (빠르게)
          goal_weight: 0.7              # 70% (덜 엄격하게)
          lookahead_base_distance: 1.6  # 160% (멀리 보기)
          xy_goal_tolerance: 1.2        # 120% (관대하게)
          goal_reached_threshold: 1.3   # 130% (관대한 도달 판정)
        overrides:
          min_linear_velocity: 0.0
          
      6:  # 감속(느리게 전진)  
        description: "Slow forward movement"
        multipliers:
          max_linear_velocity: 0.3      # 30% (느리게)
          goal_weight: 1.3              # 130% (조금 더 정확하게)
          lookahead_base_distance: 0.6  # 60% (짧게)
          xy_goal_tolerance: 0.8        # 80% (조금 더 엄격하게)
        overrides:
          min_linear_velocity: 0.0
          
      7:  # 일시 정지(1초)
        description: "Pause for 1 second"
        pause_duration: 1.0
        multipliers: {}
        overrides:
          max_linear_velocity: 0.0
          min_linear_velocity: 0.0
          
      8:  # 일시 정지(4초)
        description: "Pause for 4 seconds"  
        pause_duration: 4.0
        multipliers: {}
        overrides:
          max_linear_velocity: 0.0
          min_linear_velocity: 0.0
          
      9:  # 끝 지점
        description: "Final destination"
        multipliers:
          max_linear_velocity: 0.5      # 50% (매우 느리게)
          goal_weight: 2.0              # 200% (정확하게)
          xy_goal_tolerance: 0.3        # 30% (엄격하게)
          lookahead_base_distance: 0.8  # 80% (짧게)
          goal_reached_threshold: 0.3   # 30% (매우 정밀한 최종 도달)
        overrides:
          min_linear_velocity: 0.0
          
      10:  # 신호등 감지
        description: "Traffic light detection mode"
        multipliers:
          max_linear_velocity: 0.6      # 60% (조심스럽게)
          goal_weight: 1.5              # 150% (정확하게)
          obstacle_weight: 1.2          # 120% (장애물 더 주의)
          lookahead_base_distance: 1.2  # 120% (조금 멀리)
        overrides:
          min_linear_velocity: 0.0
          
      11:  # 차선 무시
        description: "Lane ignore mode"
        multipliers:
          max_linear_velocity: 0.8      # 80% (조금 느리게)
          goal_weight: 1.8              # 180% (목표에 집중)
          obstacle_weight: 0.8          # 80% (차선 장애물 덜 신경)
        overrides:
          min_linear_velocity: 0.0

    # SMPPI config 파일 경로 설정 (simple_behavior_planner 패키지 내부 파일 사용)
    smppi_config_path: "smppi_params.yaml"